apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: databricks/mlflow:1.5.7
        ports:
        - containerPort: 5000
        env:
          - name: BACKEND_STORE_URI
            value: "sqlite:///mlflow.db" # or any supported backend
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort # LoadBalancer # or ClusterIP / NodePort         
